import Footer from "components/Footer";
import NavBar from "components/Navbar";
import Head from "next/head";
import React, { useEffect } from "react";
import { css } from "@emotion/react";

const UserLayout = ({ children }) => {
  return (
    <div css={styles.layout}>
      <Head>
        <title>WuXia Series</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <link rel="icon" href="/logo.jpeg" className="bg-dark" />
      </Head>
      <NavBar />
      <div css={styles.childContainer}>{children}</div>
      <Footer />
    </div>
  );
};

export default UserLayout;
const styles = {
  layout: css`
    display: flex;
    flex-direction: column;
    height: 100%;
  `,
  childContainer: css`
    flex-grow: 1;
    width: 100%;
    height: 100%;
    background: var(--color-bg-primary);
  `,
};
